Repository mineteeraa/FinalProject-IR-Backend, pull requests merged in 2022-03, with the labels that each got.

#2 Search for recipe by ingredients
  search_recipes.py
Labels: enhancement

#3 Login logout
  .gitignore
  auth/project/__init__.py
  auth/project/__pycache__/__init__.cpython-38.pyc
  auth/project/__pycache__/__init__.cpython-39.pyc
  auth/project/__pycache__/auth.cpython-38.pyc
  auth/project/__pycache__/auth.cpython-39.pyc
  auth/project/__pycache__/main.cpython-38.pyc
  auth/project/__pycache__/main.cpython-39.pyc
  auth/project/__pycache__/models.cpython-38.pyc
  auth/project/__pycache__/models.cpython-39.pyc
  auth/project/auth.py
  auth/project/main.py
  auth/project/models.py
  auth/project/templates/base.html
  auth/project/templates/index.html
  auth/project/templates/login.html
  auth/project/templates/profile.html
  auth/project/templates/signup.html
Labels: enhancement

#12 Search favourite recipe
  auth/project/db.sqlite3
  auth/project/main.py
  auth/project/search_recipes.py
  auth/project/static/css/my_css.css
  auth/project/templates/favouritelist.html
Labels: enhancement

#14 Bug fix
  auth/project/auth.py
  auth/project/db.sqlite3
  auth/project/main.py
  auth/project/search_recipes.py
  auth/project/templates/index.html
  auth/project/templates/search_ingredients_list.html
  search_recipes.py
Labels: bug

#16 Add suggestion by using search ingredients TFIDF
  auth/project/__pycache__/__init__.cpython-38.pyc
  auth/project/__pycache__/auth.cpython-38.pyc
  auth/project/__pycache__/main.cpython-38.pyc
  auth/project/__pycache__/models.cpython-38.pyc
  auth/project/__pycache__/search_recipes.cpython-38.pyc
  auth/project/db.sqlite3
  auth/project/main.py
  auth/project/search_recipes.py
  auth/project/templates/details.html
  auth/project/templates/favouritelist.html
  auth/project/templates/search_ingredients_list.html
Labels: enhancement

#18 Refactor and decorate
  auth/project/auth.py
  auth/project/db.sqlite3
  auth/project/main.py
  auth/project/search_recipes.py
  auth/project/static/css/my_css.css
  auth/project/static/css/style.css
  auth/project/static/foodPattern.webp
  auth/project/static/resources/bagOfIngredients.txt
  auth/project/static/resources/bagOfName.txt
  auth/project/templates/base.html
  auth/project/templates/details.html
  auth/project/templates/favouritelist.html
  auth/project/templates/index.html
  auth/project/templates/login.html
  auth/project/templates/profile.html
  auth/project/templates/search_ingredients.html
  auth/project/templates/search_ingredients_list.html
  auth/project/templates/search_nameFood.html
  auth/project/templates/signup.html
Labels: decorate
